version: '2'

volumes:
  minionv:

services:
  master:
    image: salt-master:v1
    build:
      context: .
      dockerfile: Dockerfile.master
    command: salt-master -l info
    volumes:
      - ./master.d:/etc/salt/master.d:ro
      - ./states/:/srv/salt/:ro
    ports:
      - "4505:4505"
      - "4506:4506"
    ulimits:
      nproc: 65535
      nofile:
        soft: 4096
        hard: 4096
  minion:
    image: salt-minion:v1
    hostname: jerry
    build:
      context: .
      dockerfile: Dockerfile.minion
    command: salt-minion -l info
    volumes:
      - ./minion.d:/etc/salt/minion.d
    depends_on:
      - master

